disabled_rules:
  - multiple_closures_with_trailing_closure
  - nesting

opt_in_rules: 
  - yoda_condition
  - anyobject_protocol
  - attributes
  - closure_spacing
  - collection_alignment  
  - contains_over_filter_is_empty
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - legacy_hashing
  - legacy_objc_type
  - legacy_random
  - let_var_whitespace
  - missing_docs
  - modifier_order
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - prohibited_interface_builder
  - unavailable_function
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call 

# configurable
  - closure_body_length
  - large_tuple

excluded:
  - Pods

file_length:
  error: 400

line_length:
  error: 120

type_body_length:
  warning: 200
  error: 250

type_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50

closure_body_length:
  error: 50

function_body_length:
  error: 50

large_tuple:
  warning: 4
  error: 5